version: '3'
services:
  database:
    image: 'postgres:latest'
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: rustnotify
      POSTGRES_PASSWORD: rustnotify
      POSTGRES_DB: rustnotify
